package AES.Model;
// Generated May 21, 2015 1:38:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer id;
     private String title;
     private Date creation;
     private String description;

    public Course() {
    }

    public Course(String title, Date creation, String description) {
       this.title = title;
       this.creation = creation;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


