package AES.Model;
// Generated May 21, 2015 1:38:17 PM by Hibernate Tools 4.3.1



/**
 * CoursetraineeId generated by hbm2java
 */
public class CoursetraineeId  implements java.io.Serializable {


     private int courseid;
     private int traineeid;

    public CoursetraineeId() {
    }

    public CoursetraineeId(int courseid, int traineeid) {
       this.courseid = courseid;
       this.traineeid = traineeid;
    }
   
    public int getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(int courseid) {
        this.courseid = courseid;
    }
    public int getTraineeid() {
        return this.traineeid;
    }
    
    public void setTraineeid(int traineeid) {
        this.traineeid = traineeid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoursetraineeId) ) return false;
		 CoursetraineeId castOther = ( CoursetraineeId ) other; 
         
		 return (this.getCourseid()==castOther.getCourseid())
 && (this.getTraineeid()==castOther.getTraineeid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCourseid();
         result = 37 * result + this.getTraineeid();
         return result;
   }   


}


