package AES.Model;
// Generated May 26, 2015 3:00:19 PM by Hibernate Tools 4.3.1



/**
 * Coursetrainee generated by hbm2java
 */
public class Coursetrainee  implements java.io.Serializable {


     private CoursetraineeId id;

    public Coursetrainee() {
    }

    public Coursetrainee(CoursetraineeId id) {
       this.id = id;
    }
   
    public CoursetraineeId getId() {
        return this.id;
    }
    
    public void setId(CoursetraineeId id) {
        this.id = id;
    }




}


