package AES.Model;
// Generated 05 21, 15 2:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Examrecords generated by hbm2java
 */
public class Examrecords  implements java.io.Serializable {


     private Integer id;
     private Integer examid;
     private Integer userid;
     private Integer score;
     private Date dateTaken;

    public Examrecords() {
    }

    public Examrecords(Integer examid, Integer userid, Integer score, Date dateTaken) {
       this.examid = examid;
       this.userid = userid;
       this.score = score;
       this.dateTaken = dateTaken;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getExamid() {
        return this.examid;
    }
    
    public void setExamid(Integer examid) {
        this.examid = examid;
    }
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }




}


