package AES.Model;
// Generated May 26, 2015 3:00:19 PM by Hibernate Tools 4.3.1



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private int userid;
     private User user;
     private String firsname;
     private String lastname;

    public Userinfo() {
    }

	
    public Userinfo(User user) {
        this.user = user;
    }
    public Userinfo(User user, String firsname, String lastname) {
       this.user = user;
       this.firsname = firsname;
       this.lastname = lastname;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirsname() {
        return this.firsname;
    }
    
    public void setFirsname(String firsname) {
        this.firsname = firsname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


