package AES.Model;
// Generated May 28, 2015 3:54:45 PM by Hibernate Tools 4.3.1



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private int userid;
     private User user;
     private Integer age;
     private String firstname;
     private String lastname;
     private String department;
     private Integer position;

    public Userinfo() {
    }

	
    public Userinfo(User user) {
        this.user = user;
    }
    public Userinfo(User user, Integer age, String firstname, String lastname, String department, Integer position) {
       this.user = user;
       this.age = age;
       this.firstname = firstname;
       this.lastname = lastname;
       this.department = department;
       this.position = position;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }




}


